config/routes.rb
Rails.application.routes.draw do
  resources :albums, only: :index

  resources :models, only: :index do
    resources :albums, only: :index
  end

  resources :sites, only: :index do
    resources :albums, only: :index
  end

  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :site
  belongs_to :artist, optional: true

  has_many :album_models, dependent: :destroy
  has_many :site_models, through: :album_models
  has_many :models, through: :site_models

  delegate :title, :url, to: :site, prefix: true
  delegate :affiliate_id, :webmaster_account, to: :site, prefix: false
end

app/models/album_model.rb
class AlbumModel < ApplicationRecord
  belongs_to :album
  belongs_to :site_model
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  has_many :site_models, dependent: :destroy
  has_many :sites, through: :site_models
  has_many :albums, -> { order(date: :desc) }, through: :site_models

  validates :name, presence: true

  def latest_album
    albums.first
  end
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :albums, dependent: :destroy
  has_many :site_models, dependent: :destroy
  has_many :models, through: :site_models

  validates :title, presence: true
  validates :url, presence: true

  # FIXME: Remove hardcoded
  def affiliate_id # rubocop:disable Metrics/MethodLength
    ids = {
      'Femjoy' => FemjoyImporter::AFFILIATE_ID,
      'Joymii' => FemjoyImporter::AFFILIATE_ID,
      'AvaDawn.com' => BellaCashImporter::AFFILIATE_ID,
      'Bryci.com' => BellaCashImporter::AFFILIATE_ID,
      'KatieBanks.com' => BellaCashImporter::AFFILIATE_ID,
      'TaliaShepard.com' => BellaCashImporter::AFFILIATE_ID,
      'HunterLeigh.com' => BellaCashImporter::AFFILIATE_ID,
      'BellaNextDoor.com' => BellaCashImporter::AFFILIATE_ID,
      'JanaFox.com' => BellaCashImporter::AFFILIATE_ID,
      'CeceSeptember.com' => BellaCashImporter::AFFILIATE_ID,
      'IslaWhite.com' => BellaCashImporter::AFFILIATE_ID,
      'AlexisMonroe.com' => BellaCashImporter::AFFILIATE_ID,
      'MonroeLee.com' => BellaCashImporter::AFFILIATE_ID,
      'Watch4Beauty' => Bcash4youImporter::AFFILIATE_ID
    }
    ids[title]
  end

  # FIXME: Remove hardcoded
  def webmaster_account # rubocop:disable Metrics/MethodLength
    ids = {
      'Femjoy' => '927141-0000',
      'Joymii' => '927141-0000',
      'AvaDawn.com' => '911444-0000',
      'Bryci.com' => '911444-0000',
      'KatieBanks.com' => '911444-0000',
      'TaliaShepard.com' => '911444-0000',
      'HunterLeigh.com' => '911444-0000',
      'BellaNextDoor.com' => '911444-0000',
      'JanaFox.com' => '911444-0000',
      'CeceSeptember.com' => '911444-0000',
      'IslaWhite.com' => '911444-0000',
      'AlexisMonroe.com' => '911444-0000',
      'MonroeLee.com' => '911444-0000',
      'Watch4Beauty' => '930360-0000'
    }
    ids[title]
  end
end

app/models/site_model.rb
class SiteModel < ApplicationRecord
  belongs_to :site
  belongs_to :model

  has_many :album_models, dependent: :destroy
  has_many :albums, through: :album_models
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = base_scope.
              includes(:site, :site_models).
              order('date IS NULL, date DESC').
              page(page).
              decorate
  end

  private

  def base_scope
    model&.albums || site&.albums || Album.all
  end

  def model
    @model = Model.find_by(id: params[:model_id])
  end

  def site
    @site = Site.find_by(id: params[:site_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def page
    [params[:page].to_i, 0].max
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    @models = Model.
              includes(:site_models, albums: :site).
              order(:name).
              page(page).
              decorate
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.
             includes(:albums).
             order(:title).
             page(page).
             decorate
  end
end

app/views/albums/_album.html.slim
.album[id="#{dom_id(album)}"]
  h2.title
    = link_to album.title, album.affiliated_url
    '
    'from
    = link_to album.site_title, site_albums_path(album.site)
  .models
    span
      'Starring:
      '
      strong
        - album.site_models.each do |site_model|
          = link_to site_model.nickname, model_albums_path(site_model.model)
      ', added on
      strong = album.date
  .image
    = link_to album.affiliated_url do
      = image_tag album.cover_url, class: 'img-fluid img-thumbnail mx-auto d-block'

app/views/albums/index.html.slim
= render @albums
= render 'shared/pagination', collection: @albums

app/views/layouts/application.html.slim
doctype html
html
  head
    title Nude Angels - nude photos, albums, videos

    meta charset='utf-8'
    meta name='distribution' content='global'
    meta name='author' content='NudeAngels - The nude art and photo archive'
    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
    meta name='desription' content='nudeangels nude art and photo archive from FEMJOY, WATCH4BEAUTY and many more'
    meta name='resource-type' content='document'
    meta name='robots' content='all, index, follow'

    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/navigation'
    .container
      main.ml-sm-auto.pt-3
        = yield

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/models/_model.html.slim
.model[id="#{dom_id(model)}"]
  h2.title = model.name

  .akas
    strong AKA:
    '
    - model.site_models.each do |site_model|
      span
        = site_model.nickname

  .albums
    strong Albums:
    '
    = link_to model.albums.size, model_albums_path(model)

  .image
    = link_to model.latest_album.affiliated_url do
      = image_tag model.latest_album.cover_url, class: 'img-fluid img-thumbnail mx-auto d-block'

app/views/models/index.html.slim
= render @models
= render 'shared/pagination', collection: @models

app/views/shared/_navigation.html.slim
nav.navbar.navbar-expand-md.navbar-toggleable-md.navbar-dark.fixed-top.bg-dark
  .navbar-brand
    ' Nude Angels

  button.navbar-toggler.d-lg-none type='button' data-toggle='collapse' data-target='#navbarsMain' aria-controls='navbarsMain' aria-expanded='false' aria-label='Toggle navigation'
    span.navbar-toggler-icon

  .collapse.navbar-collapse#navbarsMain
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to 'Albums', albums_path, class: 'nav-link'
      li.nav-item
        = link_to 'Models', models_path, class: 'nav-link'
      li.nav-item
        = link_to 'Sites', sites_path, class: 'nav-link'

    = form_for root_path, method: :get, html: { class: 'form-inline mt-2 mt-md-0' } do |form|
      = form.text_field 'query', class: 'form-control mr-sm-2', placeholder: 'Search', 'aria-label': 'Search'
      = form.button 'Search', type: :submit, class: 'btn btn-outline-success my-2 my-sm-0'

app/views/shared/_pagination.html.slim
nav
  ul.pagination.pagination-lg.justify-content-center
    - unless collection.first_page?
      li.page-item
        = link_to_prev_page collection, '&laquo; Prev'.html_safe, class: 'page-link', role: 'button', tabindex: -1
    - unless collection.last_page?
      li.page-item
        = link_to_next_page collection, 'Next &raquo;'.html_safe, class: 'page-link', role: 'button'

app/views/sites/_site.html.slim
.site[id="#{dom_id(site)}"]
  h2.title = link_to site.title, site.url

  .albums
    strong Albums:
    '
    = link_to site.albums.size, site_albums_path(site)

app/views/sites/index.html.slim
= render @sites
= render 'shared/pagination', collection: @sites